#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# project2.tcl: Tcl script for re-creating project 'project2'
#
# Generated by Vivado on Fri Sep 05 14:48:02 +0800 2025
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project2.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "srcs/sources_1/ip/pool_buffer/pool_buffer.xci"
#    "srcs/sources_1/ip/P2P_buffer/P2P_buffer.xci"
#    "srcs/sources_1/ip/pixel_window_block/pixel_window_block.xci"
#    "srcs/sources_1/new/DSU.v"
#    "srcs/sources_1/new/compute_engine.v"
#    "srcs/sources_1/new/compute_engine_p.v"
#    "srcs/sources_1/new/control_unit.v"
#    "srcs/sources_1/new/depthwise.v"
#    "srcs/sources_1/new/flatten.v"
#    "srcs/sources_1/new/full_connect.v"
#    "srcs/sources_1/new/input_buffer_block.v"
#    "srcs/sources_1/new/intermediate_buffer.v"
#    "srcs/sources_1/new/intermediate_buffer2.v"
#    "srcs/sources_1/new/max_pool.v"
#    "srcs/sources_1/new/multiply_unit.v"
#    "srcs/sources_1/new/pixel_window.v"
#    "srcs/sources_1/new/pointwise.v"
#    "srcs/sources_1/new/pool.v"
#    "srcs/sources_1/new/TOP.v"
#    "srcs/sources_1/new/T.v"
#    "weights_8bit/plane.coe"
#    "weights_8bit/conv_depth.weight.coe"
#    "weights_8bit/conv_point.weight.coe"
#    "weights_8bit/fc1_weight.coe"
#    "weights_8bit/fc2_weight.coe"
#    "srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci"
#    "srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci"
#    "srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci"
#    "srcs/sources_1/ip/D2P_buffer/D2P_buffer.xci"
#    "srcs/sources_1/ip/point_weight_rom/point_weight_rom.xci"
#    "srcs/sources_1/ip/depth_weight_rom/depth_weight_rom.xci"
#    "srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci"
#    "srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci"
#    "srcs/constrs_1/new/top.xdc"
#    "srcs/sim_1/new/TOP_tb.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "project2"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project2.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg400-2" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "127" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "127" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "127" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "127" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "127" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "127" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "127" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "819" -objects $obj
set_property -name "xpm_libraries" -value "XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/pool_buffer/pool_buffer.xci" ]\
 [file normalize "${origin_dir}/srcs/sources_1/ip/P2P_buffer/P2P_buffer.xci" ]\
 [file normalize "${origin_dir}/srcs/sources_1/ip/pixel_window_block/pixel_window_block.xci" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/DSU.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/compute_engine.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/compute_engine_p.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/control_unit.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/depthwise.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/flatten.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/full_connect.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/input_buffer_block.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/intermediate_buffer.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/intermediate_buffer2.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/max_pool.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/multiply_unit.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/pixel_window.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/pointwise.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/pool.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/TOP.v" ]\
 [file normalize "${origin_dir}/srcs/sources_1/new/T.v" ]\
 [file normalize "${origin_dir}/weights_8bit/plane.coe" ]\
 [file normalize "${origin_dir}/weights_8bit/conv_depth.weight.coe" ]\
 [file normalize "${origin_dir}/weights_8bit/conv_point.weight.coe" ]\
 [file normalize "${origin_dir}/weights_8bit/fc1_weight.coe" ]\
 [file normalize "${origin_dir}/weights_8bit/fc2_weight.coe" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "pool_buffer/pool_buffer.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "P2P_buffer/P2P_buffer.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "pixel_window_block/pixel_window_block.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "TOP" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blk_mem_gen_2/blk_mem_gen_2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blk_mem_gen_1/blk_mem_gen_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blk_mem_gen_0/blk_mem_gen_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/D2P_buffer/D2P_buffer.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "D2P_buffer/D2P_buffer.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/point_weight_rom/point_weight_rom.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "point_weight_rom/point_weight_rom.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/depth_weight_rom/depth_weight_rom.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "depth_weight_rom/depth_weight_rom.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blk_mem_gen_3/blk_mem_gen_3.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blk_mem_gen_4/blk_mem_gen_4.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/srcs/constrs_1/new/top.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/top.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files *new/top.xdc]" -objects $obj
set_property -name "target_part" -value "xc7z020clg400-2" -objects $obj
set_property -name "target_ucf" -value "[get_files *new/top.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/srcs/sim_1/new/TOP_tb.v" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "TOP_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "300us" -objects $obj
set_property -name "xsim.simulate.saif" -value "power_tutorial_timing_xsim.saif" -objects $obj
set_property -name "xsim.simulate.saif_all_signals" -value "1" -objects $obj

